inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails

AllCops:
  Exclude:
    - "tmp/**/*"
    - "config/initializers/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "db/migrate/*.rb"
    - "bin/*"
  DisplayCopNames: true
  TargetRubyVersion: 2.7.4

LineLength:
  Max: 180

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

AsciiComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Etrics/MethodLength:
  Enabled: true
  Max: 18

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
  Max: 200

Metrics/AbcSize:
  Enabled: true
  Max: 23

Style/GuardClause:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

GlobalVars:
  AllowedVariables: [$CFLAGS, $LIBS]
